version: '3.3'
services:
  backend: 
    build: 
      context: api
      args: 
        env: dev
    command: /app/start-reload.sh
    volumes:
      - ./api:/app
    environment:
      - POSTGRES_PASSWD=test
      - POSTGRES_USER=fisher
      - POSTGRES_SERVER=db:5432
      - POSTGRES_DB=fisher
    ports:
      - '8000:8000'
    depends_on: 
      - db
  db:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=fisher
      - POSTGRES_DB=fisher
  pg_tileserv:
    image: pramsey/pg_tileserv
    ports:
      - "7800:7800"
    environment:
      - DATABASE_URL=postgres://fisher:test@db:5432/fisher
    depends_on:
      - db
    entrypoint: sh -c "sleep 10; /app/pg_tileserv"
volumes:
  db-data:
